name = 'isfreader'
version = '1.2.0'
description = 'Read tek scope isf files as a numpy array.'
url = 'https://github.com/justengel/isfreader'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
